directories:
  output: dist-electron
  buildResources: public
appId: com.taskflowpro.app
productName: TaskFlow Pro
files:
  - filter:
      - dist/**/*
      - main.js
      - public/preload.js
      - node_modules/**/*
      - '!node_modules/.cache'
      - '!node_modules/.vite'
mac:
  category: public.app-category.productivity
  target:
    - target: dmg
      arch:
        - x64
        - arm64
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
  requestedExecutionLevel: asInvoker
  artifactName: ${productName}-${version}-${arch}.${ext}
  sign: null
  verifyUpdateCodeSignature: false
  certificateFile: null
  certificatePassword: <stripped sensitive data>
linux:
  target:
    - target: AppImage
      arch:
        - x64
    - target: deb
      arch:
        - x64
  category: Office
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  allowElevation: false
  perMachine: false
electronVersion: 28.3.3
